### ISSUE TITLE
Upgrade to Bootstrap 4 once out of alpha/beta

### ISSUE THREAD

**Issue by jeffgreco** [patronage/bubs#18]
It's still in alpha, but there will be lots of advantages:
- Better grids + flexbox
- Built natively in SASS
- rem/em sizing because...

Cons:
- Drops IE8

**Comment by ccorda** [comment]
I'll add one more con: ruins the nice bliss of having every site (at least that we've built over 3 years), using the exact same version.  But can only swim upstream on that one for so long.

Any idea when bootstrap 4 will be done?

**Comment by jeffgreco** [comment]
Nope! They are in Alpha 3, so it will be a while.

This needs a "future" tag or something like that.

**Comment by jeffgreco** [comment]
They're in alpha 5, but it is definitely not beta stable yet. Lots of changes coming in alpha 6. 

Also noting this page: https://v4-alpha.getbootstrap.com/migration/

**Comment by ccorda** [comment]
@jeffgreco anything in it you're excited about?

**Comment by jeffgreco** [comment]
Lots of incremental improvements but biggest thing by far is flexbox layout.

**Comment by ccorda** [comment]
What does that get you? Something like ability to make all columns equal heights would be a nice practical win.

**Comment by yuvilio** [comment]
Seems like they cite that as a reason among other flexbox faves (vertical aligntment, column reordering)

http://v4-alpha.getbootstrap.com/getting-started/flexbox/#why-flexbox (edited)

**Comment by kylehotchkiss** [comment]
Been playing with bootstrap 4 a little bit in free time. Grid is retained, some small form changes needed (biggest thing i noticed was removal of `help-block`). Built in hamburger menus! and being able to do 5 evenly spaced columns with just `.cols` is really nice.

I'd need to see it on a client site to see how backwards-compatible it _really_ is but I thought they would change up the grid more than they did.

**Comment by ccorda** [comment]
Re IE8, did some looking at various GA accounts and it's all but dead (as are IE9 and IE 10) -- all in the 0.1% range of users for the month.

So we can upgrade jQuery to 3 which is what bootstrap uses.

**Comment by kylehotchkiss** [comment]
<img width="523" alt="screen shot 2017-10-23 at 4 14 37 pm" src="https://user-images.githubusercontent.com/108172/31917646-620daa0a-b80d-11e7-83c2-ae5e1d70b126.png">

Some of our size variables need to be ported to bootstrap (Or css'?) new variable format

**Comment by ccorda** [comment]
Are you referring to media queries like @include sm-and-up {}?, or just the actual variable sizes themselves?

**Comment by kylehotchkiss** [comment]
Variable sizes themselves, like `$screen-sm-min` in `_breakpoints.scss`.

```
@mixin sm {
    @media #{screen} and (min-width: #{$screen-sm-min}) and (max-width: #{$screen-sm-max}) {
        @content;
    }
}
```

**Comment by ccorda** [comment]
the need for our own _breakpoints is deprecated, it's now baked into bootstrap:
https://getbootstrap.com/docs/4.0/layout/overview/#responsive-breakpoints

**Comment by yuvilio** [comment]
The theme is now upgraded to the latest bootstrap 4 beta! Per #84 .
