### ISSUE TITLE
Deploy script; if you forget target, you get left in deploy branch

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs#31]
If you end up making a bunch of changes in deploy branch on accident, it can be pretty difficult to get back to master. We need to ensure no matter what happens with deploy, the user always ends back up in master.

Higher priority.

**Comment by ccorda** [comment]
One adjustment, if a user is on a branch, they should go back to the branch, not master.

We already have this in success cases:

```
echo "Returning to working branch..."
git stash
git checkout $branch
```

I think the solution here would be to catch any error

If you play with this, keep in mind I recently added new code to resolve #26.

**Comment by kylehotchkiss** [comment]
I actually realized that we had non-master working branches and forgot to add it, good call :D

**Comment by ccorda** [comment]
potential solution:
http://linuxcommand.org/wss0150.php
