### ISSUE TITLE
Remove JS bundling/concatenation

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs#34]
Minification and gzip are still good, but bundling everything into one big JS file is actually an [antipattern](http://stackoverflow.com/questions/30861591/why-bundle-optimizations-are-no-longer-a-concern-in-http-2)

[WP Engine](http://stackoverflow.com/questions/30861591/why-bundle-optimizations-are-no-longer-a-concern-in-http-2) has HTTP2 (if you have SSL).

I propose something like this, which would let you still have a single version of libs, but make each page only load what it needs.

`template-something.twig`:

```
{% load_footer_scripts = [1, 2] %}
```

`layout.twig`:

```
{% if 'slick' in load_footer_scripts %}
    <script src="{{ function("rev", "vendor/slick-carousel/slick/slick.js") }}"></script>
{% endif %}
```

Individual pages could either load JS inline using `{% block footer_scripts %}`, or make a call to something in `js/pages/something-complicated.js

**Comment by ccorda** [comment]
Good overview I found explaining http2:
https://blog.cloudflare.com/http-2-for-web-developers/

**Comment by kylehotchkiss** [comment]
Before we embrace, do modern android and iOS browsers support this? If not, this is gonna make mobile sites a little bit slower.

**Comment by ccorda** [comment]
@kylehotchkiss they do. 

Note that for all of these, you need to be using HTTPS:
http://caniuse.com/#feat=http2

But with it being free on wpengine via let's encrypt, there is no reason we shouldn't be doing that.

**Comment by kylehotchkiss** [comment]
<img width="483" alt="screen shot 2016-12-15 at 1 30 07 pm" src="https://cloud.githubusercontent.com/assets/108172/21236865/9ff7c668-c2ca-11e6-811a-5b57078231ce.png">

I don't understand android breakdown worldwide vs usa but seeing 8% not supporting some recentt android browser

**Comment by ccorda** [comment]
I skipped the asset loading bit: `{% load_footer_scripts = [1, 2] %}`, but otherwise this is good to go. It was a little tricky handling files that might be in any directory (including vendor), but updated useref to copy everything to dist, and added a `revBlock` function that loops through all files and applies rev to them.
