### ISSUE TITLE
Evaluate Google Analytics Autotracker

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs#35]
[Google has a new tool out for autotracking](https://github.com/googleanalytics/autotrack) a lot of neat stuff on websites, which could provide a good tool for some interesting analytics reports.

* Enables declarative event tracking, via HTML attributes in the markup. (ez downloads reporting)
* Allows you to track when elements are visible within the viewport. (do people finish reading blog posts)
* Enables tracking media query matching and media query changes.
* Automatically tracks link clicks to external domains. (i thought GA did this already but knowing how people exit the site could provide some interesting perspectives)
* Tracks page visibility state changes, which enables much more accurate session, session duration, and pageview metrics. 
* Automatically tracks URL changes for single page applications.

**Comment by ccorda** [comment]
Used this today, I thought it was great.

* I found the event tracker handy
* Currently we disable in dev, instead I think we should use `ga('set', 'sendHitTask', null);`
* I like the idea of multi-section homepage tracking
