### ISSUE TITLE
Need for ACF Pro url breaks composer install

### ISSUE THREAD

**Issue by jeffgreco** [patronage/bubs#38]
Currently the ACF Pro plugin location is set to path.to/acf and it fatally breaks the install process.

We should do some combination of:
- Document this
- Make it optional
- Make it a more sensible default (maybe "acf.zip" placed in the root?)

**Comment by ccorda** [comment]
There is now a dummy zip file that has an `empty.txt` that has this message:

> Replace this with a valid licensed link to ACF zip.

I'm working on a manual steps wiki page for #17, I'll be sure and cover updating ACF in there.

Thanks for filing @jeffgreco, gonna close out now.
