### ISSUE TITLE
Set up mobile nav

### ISSUE THREAD

**Issue by sscummings** [patronage/bubs#44]
https://getbootstrap.com/examples/navbar/

**Comment by ccorda** [comment]
I would vote we just go with a more basic collapse menu we're in control of and do away with that navbar -- it's really tough to style, and we almost never use it the way the bootstrap docs do

**Comment by jeffgreco** [comment]
The next version: http://v4-alpha.getbootstrap.com/components/navbar/

**Comment by ccorda** [comment]
https://github.com/CWSpear/bootstrap-hover-dropdown/issues/153

I think we might need to host this lib inside of the repo, so we can hard-code in that fix.

**Comment by ccorda** [comment]
No longer applicable with cleaner navbar markup in bootstrap 4, closing out.
