### ISSUE TITLE
Git ignore filemode after cloning projects

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs#82]
Can `git config core.fileMode false` run post-clone?

**Comment by ccorda** [comment]
Is it not already running? https://github.com/patronage/bubs/blob/master/_build/hook-post-merge.sh#L17

**Comment by kylehotchkiss** [comment]
I didn't see any hooks run after I pulled -- but it's possible that `nvm` changes between projects effectively uninstalled husky for me:

```
▲ healthcarevoter.dev at master ✔ npm ls --global | grep husky
▲ healthcarevoter.dev at master ✔ 
```

**Comment by ccorda** [comment]
believe this is working via the post-merge hook.
